### ISSUE TITLE
CommonTest.testCountLines Fail

### ISSUE THREAD

**Issue by yujiaao** [OrhanKupusoglu/sloc-maven-plugin#3]
```
kupusoglu.orhan.sloc_maven_plugin.engine.CommonTest.
testCountLines
Failed
0.03s
Message:
N/A
Stack trace:
org.junit.ComparisonFailure: SLOC - failure expected:<...--------+----------+[]> but was:<...--------+----------+[

]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at kupusoglu.orhan.sloc_maven_plugin.engine.CommonTest.testCountLines(CommonTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
the `actual` is a LineFeed more than `expected`

**Comment by OrhanKupusoglu** [comment]
On which OS are you testing?
On Linux it must be OK.

**Comment by OrhanKupusoglu** [comment]
Please check the last commit.

**Comment by yujiaao** [comment]
Windows 10

**Comment by OrhanKupusoglu** [comment]
This issue is too old & cold by now.
Feel free to re-open if you think the provided solution does not solve the issue.

**Comment by OrhanKupusoglu** [comment]
The commit mentioned was 508763f.
